version: "3"
services:
  mssql:
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'SuperSecretP@ssw0rd!'
    ports:
      - '1433:1433'
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
